"""
Lecture Prep with Cortex — generates a downloadable PPTX from lecture material.
"""

import io
import os
import uuid
import logging
from typing import Optional

import fitz  # PyMuPDF
from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, Form
from fastapi.responses import Response
from sqlalchemy.orm import Session

import app.models as models
from app.database import get_db
from app.auth import get_current_user

log = logging.getLogger(__name__)
router = APIRouter(prefix="/api/lecture-prep", tags=["Lecture Prep"])

MAX_MATERIAL_CHARS = 60_000

# In-memory store: presentation_id -> pptx bytes (TTL handled by session lifecycle)
_store: dict[str, bytes] = {}


# ── Slide colours ─────────────────────────────────────────────────────────────
try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN
    _PPTX_OK = True
except ImportError:
    _PPTX_OK = False

BG     = (0x0F, 0x17, 0x2A)
ACCENT = (0x4F, 0x46, 0xE5)
WHITE  = (0xFF, 0xFF, 0xFF)
LIGHT  = (0xE2, 0xE8, 0xF0)
MUTED  = (0x94, 0xA3, 0xB8)


def _rgb(t): return RGBColor(*t)


def _rect(slide, l, t, w, h, fill=None):
    from pptx.util import Emu
    from pptx.enum.shapes import MSO_SHAPE_TYPE
    shp = slide.shapes.add_shape(1, l, t, w, h)
    if fill:
        shp.fill.solid()
        shp.fill.fore_color.rgb = _rgb(fill)
    else:
        shp.fill.background()
    shp.line.fill.background()
    return shp


def _txt(slide, l, t, w, h, text, size, bold=False, color=WHITE, align=None):
    from pptx.enum.text import PP_ALIGN
    align = align or PP_ALIGN.LEFT
    txb = slide.shapes.add_textbox(l, t, w, h)
    txb.word_wrap = True
    tf = txb.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = _rgb(color)
    run.font.name = "Calibri"
    return txb


def _build_pptx(data: dict) -> bytes:
    if not _PPTX_OK:
        raise HTTPException(500, "python-pptx not installed on this server")

    prs = Presentation()
    prs.slide_width  = Inches(13.33)
    prs.slide_height = Inches(7.5)
    blank = prs.slide_layouts[6]  # blank layout

    W, H = Inches(13.33), Inches(7.5)
    title_text = data.get("title", "Lecture Presentation")
    subject    = data.get("subject", "")
    slides     = data.get("slides", [])

    # ── Title slide ──────────────────────────────────────────────────────
    s = prs.slides.add_slide(blank)
    s.background.fill.solid()
    s.background.fill.fore_color.rgb = _rgb(BG)

    _rect(s, Inches(0), Inches(0), Inches(0.6), H, ACCENT)           # left bar
    _rect(s, Inches(0.6), Inches(5.3), Inches(12.73), Inches(0.06), ACCENT)  # rule

    _txt(s, Inches(1), Inches(2.3), Inches(11.5), Inches(1.6),
         title_text, 44, bold=True, color=WHITE)
    if subject:
        _txt(s, Inches(1), Inches(4.1), Inches(11.5), Inches(0.7),
             subject, 22, color=LIGHT)
    _txt(s, Inches(1), Inches(6.7), Inches(6), Inches(0.5),
         "Generated by Cortex AI", 11, color=MUTED)

    # ── Content slides ────────────────────────────────────────────────────
    for idx, info in enumerate(slides):
        s = prs.slides.add_slide(blank)
        s.background.fill.solid()
        s.background.fill.fore_color.rgb = _rgb(BG)

        # header bar
        _rect(s, Inches(0), Inches(0), W, Inches(1.25), ACCENT)
        # slide title
        _txt(s, Inches(0.4), Inches(0.18), Inches(12.5), Inches(0.9),
             info.get("title", ""), 30, bold=True, color=WHITE)

        # bullets
        bullets = info.get("bullets", [])[:6]
        y0 = Inches(1.5)
        bh = Inches(0.72)
        for i, bullet in enumerate(bullets):
            y = y0 + i * bh
            _rect(s, Inches(0.55), y + Inches(0.27), Inches(0.12), Inches(0.12), ACCENT)
            _txt(s, Inches(0.82), y, Inches(11.7), bh, bullet, 18, color=LIGHT)

        # speaker notes
        notes = info.get("notes", "")
        if notes:
            s.notes_slide.notes_text_frame.text = notes

        # slide number
        _txt(s, Inches(12.5), Inches(7.1), Inches(0.7), Inches(0.35),
             str(idx + 2), 11, color=MUTED)

    out = io.BytesIO()
    prs.save(out)
    return out.getvalue()


# ── Claude slide generation ───────────────────────────────────────────────────

_SLIDES_TOOL = {
    "name": "create_presentation",
    "description": "Create a structured lecture presentation from the provided material.",
    "input_schema": {
        "type": "object",
        "properties": {
            "title": {"type": "string", "description": "Concise presentation title"},
            "subject": {"type": "string", "description": "One-line course/topic description for the subtitle"},
            "slides": {
                "type": "array",
                "description": "Content slides (do not include a separate title slide — that is generated automatically)",
                "items": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string", "description": "Slide heading, max 8 words"},
                        "bullets": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "3-5 bullet points. Each bullet max 20 words, no sub-bullets.",
                        },
                        "notes": {"type": "string", "description": "Lecturer speaker notes, 1-3 sentences"},
                    },
                    "required": ["title", "bullets"],
                },
            },
        },
        "required": ["title", "subject", "slides"],
    },
}


def _call_claude(material_text: str, prefs: dict) -> dict:
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        raise HTTPException(500, "AI service not configured")

    import anthropic
    client = anthropic.Anthropic(api_key=api_key)

    num_slides = prefs.get("num_slides", "auto")
    level      = prefs.get("level", "undergraduate")
    focus      = prefs.get("focus", "key concepts and main points")
    tone       = prefs.get("tone", "academic")
    notes      = prefs.get("include_notes", True)

    slide_target = {
        "10-15": "10 to 15", "15-20": "15 to 20",
        "20-30": "20 to 30", "auto": "an appropriate number (usually 12-18)",
    }.get(num_slides, "an appropriate number")

    system = f"""You are an expert educational content designer creating professional lecture slides.

Extract and organise the lecture material into a clear, well-structured presentation.

PREFERENCES:
- Slides: {slide_target} content slides (not counting the title slide)
- Student level: {level}
- Emphasis: {focus}
- Tone: {tone}
- Speaker notes: {"include thoughtful speaker notes for each slide" if notes else "no speaker notes needed"}

SLIDE RULES:
- Each slide: 3-5 short bullet points (max 20 words each)
- Start with an Introduction / Overview slide
- Group related content logically
- End with a Summary or Key Takeaways slide
- Slide titles: concise, max 8 words
- Do NOT include the title slide in the slides array — it is generated automatically"""

    response = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=4096,
        system=system,
        messages=[{"role": "user", "content": f"<lecture_material>\n{material_text}\n</lecture_material>"}],
        tools=[_SLIDES_TOOL],
        tool_choice={"type": "tool", "name": "create_presentation"},
    )

    for block in response.content:
        if block.type == "tool_use" and block.name == "create_presentation":
            return block.input

    raise HTTPException(500, "AI failed to generate slide content. Please try again.")


# ── Text extraction ───────────────────────────────────────────────────────────

def _extract_text(data: bytes, mime: str) -> str:
    if "pdf" in mime or mime == "application/octet-stream":
        try:
            doc = fitz.open(stream=data, filetype="pdf")
            return "\n".join(p.get_text() for p in doc)[:MAX_MATERIAL_CHARS]
        except Exception:
            pass
    # Plain text / docx fallback
    try:
        return data.decode("utf-8", errors="ignore")[:MAX_MATERIAL_CHARS]
    except Exception:
        return ""


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.post("/generate")
async def generate_slides(
    file: UploadFile = File(...),
    title: str = Form(""),
    num_slides: str = Form("auto"),
    level: str = Form("undergraduate"),
    focus: str = Form(""),
    tone: str = Form("academic"),
    include_notes: bool = Form(True),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    if current_user.role != models.RoleEnum.lecturer:
        raise HTTPException(403, "Only lecturers can generate presentations")

    raw = await file.read()
    if not raw:
        raise HTTPException(400, "Uploaded file is empty")

    material_text = _extract_text(raw, file.content_type or "")
    if not material_text.strip():
        raise HTTPException(400, "Could not extract text from the file. Please use a PDF or plain-text document.")

    prefs = {
        "num_slides": num_slides,
        "level": level,
        "focus": focus or "key concepts and main points",
        "tone": tone,
        "include_notes": include_notes,
    }

    slide_data = _call_claude(material_text, prefs)

    # Override title if the lecturer provided one
    if title.strip():
        slide_data["title"] = title.strip()

    pptx_bytes = _build_pptx(slide_data)

    presentation_id = str(uuid.uuid4())
    _store[presentation_id] = pptx_bytes

    # Return outline + id so the frontend can preview and then download/save
    return {
        "presentation_id": presentation_id,
        "title": slide_data.get("title", ""),
        "subject": slide_data.get("subject", ""),
        "slide_count": len(slide_data.get("slides", [])) + 1,  # +1 for title slide
        "outline": [s.get("title", "") for s in slide_data.get("slides", [])],
    }


@router.get("/download/{presentation_id}")
def download_presentation(
    presentation_id: str,
    current_user: models.User = Depends(get_current_user),
):
    pptx = _store.get(presentation_id)
    if not pptx:
        raise HTTPException(404, "Presentation not found or expired. Please generate again.")

    return Response(
        content=pptx,
        media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        headers={"Content-Disposition": f'attachment; filename="cortex-lecture.pptx"'},
    )


@router.post("/save/{class_id}")
def save_to_course(
    class_id: int,
    payload: dict,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    if current_user.role != models.RoleEnum.lecturer:
        raise HTTPException(403, "Only lecturers can save materials")

    presentation_id = payload.get("presentation_id", "")
    custom_title    = (payload.get("title") or "").strip()

    pptx = _store.get(presentation_id)
    if not pptx:
        raise HTTPException(404, "Presentation not found or expired. Please generate again.")

    cls = db.query(models.Class).filter(
        models.Class.id == class_id,
        models.Class.lecturer_id == current_user.id,
    ).first()
    if not cls:
        raise HTTPException(404, "Course not found or you don't own it")

    mat_title = custom_title or f"Lecture Slides — {cls.name}"
    filename  = f"cortex-slides-{uuid.uuid4().hex[:8]}.pptx"

    material = models.CourseMaterial(
        class_id         = class_id,
        uploaded_by      = current_user.id,
        title            = mat_title,
        description      = "Generated by Cortex AI Lecture Prep",
        original_filename= filename,
        stored_filename  = filename,
        file_type        = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        file_size        = len(pptx),
        file_data        = pptx,
    )
    db.add(material)
    db.commit()
    db.refresh(material)

    return {"message": f"Saved to {cls.name}", "material_id": material.id}
